services:
  memcache:
    container_name: PS_193165_memcache
    image: memcached
    user: 1000:1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - ps_cache_net

  prestashop:
    container_name: PS_193165
    image: henrykwolek/my-prestashop:latest
    restart: unless-stopped
    ports:
      - 19316:80
    environment:
      PS_DEV_MODE: 0
      ADMIN_MAIL: admin@prestashop.com 
      ADMIN_PASSWD: admin123
      DB_SERVER: admin-mysql_default
      DB_USER: root
      DB_NAME: BE_193165
      DB_PASSWD: student
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin123
      CACHE_SYSTEM: Memcached
    networks:
    - admin-mysql_default
    entrypoint: /init_mysql.sh

networks:
  ps_cache_net:
  admin-mysql_default:
    external: true