version: '3'
services:
  mysql:
    container_name: ebiz-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 443:443
    environment:
      ADMIN_MAIL: admin@prestashop.com 
      ADMIN_PASSWD: admin123
      DB_SERVER: ebiz-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost
      PS_FOLDER_ADMIN: admin123
    networks:
      - prestashop_network
    volumes:
      - ./prestashop:/var/www/html  # Dane PrestaShop, aby były trwałe
      - ./ssl:/etc/ssl/private  # For SSL key
      - ./ssl_certs:/etc/ssl/certs  # For SSL certificate
      - ./config:/etc/apache2/sites-available  # For Apache configuration
    command: >
      /bin/bash -c "
      update-ca-certificates &&
      a2enmod ssl &&
      a2ensite 000-default.conf &&
      apachectl -D FOREGROUND"

networks:
  prestashop_network:

volumes:
  prestashop:  # Wolumen na dane PrestaShop
