<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Account\CommandHandler\LinkShopHandler' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Account\\CommandHandler\\LinkShopHandler'] = new \PrestaShop\Module\PsAccounts\Account\CommandHandler\LinkShopHandler(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Account\\LinkShop']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Account\\LinkShop'] : $this->load('getLinkShopService.php')) && false ?: '_'});
