<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Middleware\Oauth2Middleware' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Middleware\\Oauth2Middleware'] = new \PrestaShop\Module\PsAccounts\Middleware\Oauth2Middleware(${($_ = isset($this->services['ps_accounts.module']) ? $this->services['ps_accounts.module'] : $this->load('getPsAccounts_ModuleService.php')) && false ?: '_'});
