<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Repository\ShopTokenRepository' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\ShopTokenRepository'] = new \PrestaShop\Module\PsAccounts\Repository\ShopTokenRepository(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Account\\Session\\Firebase\\ShopSession']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Account\\Session\\Firebase\\ShopSession'] : $this->load('getShopSessionService.php')) && false ?: '_'});
