<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container630kkdu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container630kkdu/appProdProjectContainer.php') {
    touch(__DIR__.'/Container630kkdu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container630kkdu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container630kkdu\appProdProjectContainer([
    'container.build_hash' => '630kkdu',
    'container.build_id' => 'd3c78d82',
    'container.build_time' => 1736721258,
], __DIR__.\DIRECTORY_SEPARATOR.'Container630kkdu');
