<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvci7qi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvci7qi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOvci7qi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOvci7qi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOvci7qi\appProdProjectContainer([
    'container.build_hash' => 'Ovci7qi',
    'container.build_id' => 'b3625322',
    'container.build_time' => 1733662041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvci7qi');
