<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7w7ajvm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7w7ajvm/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7w7ajvm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7w7ajvm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7w7ajvm\appProdProjectContainer([
    'container.build_hash' => '7w7ajvm',
    'container.build_id' => '5127b370',
    'container.build_time' => 1733246915,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7w7ajvm');
