<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLnrxue2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLnrxue2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLnrxue2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLnrxue2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLnrxue2\appProdProjectContainer([
    'container.build_hash' => 'Lnrxue2',
    'container.build_id' => '25624500',
    'container.build_time' => 1732464661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLnrxue2');
