services:
  db:
    container_name: admin-mysql_default
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: student
    ports:
      - "3306:3306"
    networks:
      - admin-mysql_default

networks:
  admin-mysql_default:
    external: true
