services:
  db:
    container_name: admin-mysql_default
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_193165  # Specify the default database to create
    ports: 
      - 3306:3306
    networks:
      - admin-mysql_default
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

networks:
  admin-mysql_default:
    external: true
