name: PS_CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: henrykwolek
          password: Ps_12345678

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t henrykwolek/my-prestashop:latest .
      - name: Push Docker Image
        run: |
          docker push henrykwolek/my-prestashop:latest
